### ISSUE TITLE
Здравствуйте

### ISSUE THREAD

**Issue by Valijonzoda** [Wolfram-180/Blablacar_bot#1]
Хотел спросить как сделать так чтобы один заказ с 4 местами выводился 1 раз, а не 4

**Comment by Wolfram-180** [comment]
Добрый день. В файле dbwork.py на строке 141 убрать обработку в цикле.

**Comment by Wolfram-180** [comment]
Добрый день. В файле dbwork.py на строке 141 убрать обработку в цикле.
